version: '3.8'

services:
  # Database
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: scorezorg
      POSTGRES_USER: scorezorg
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./apps/scorezorg/database/production-schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - "5433:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U scorezorg"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Application
  app:
    build: .
    environment:
      NODE_ENV: production
      # Internal Docker network doesn't need SSL - already isolated
      DATABASE_URL: postgresql://scorezorg:${DB_PASSWORD:-changeme}@postgres:5432/scorezorg
      # CORS configuration (defaults to * for development)
      ALLOWED_ORIGINS: ${ALLOWED_ORIGINS:-*}
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/api/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:
